### ISSUE TITLE
Not getting the refinement output from gemini api

### ISSUE THREAD

**Issue by shalini8979** [navgurukul/oscar_ai_transcription#11] opened 2024-11-22 08:18 UTC
While giving an input to oscar transcription , then the output comes without grammatical refinement this is because we add a code for showing the output which is same as given input whenever we faced any error from gemini api .
Details : https://app.slack.com/client/T01N1V0GHGV/C07JFP271J5
![Screenshot_20241119_192654](https://github.com/user-attachments/assets/e0ab1f91-3bfc-4d92-a604-58ac9d2ebaa0)
Reported by : Souvik

**Comment by surajsahani** [comment] 2024-11-22 09:34
Duplicate to which issue @shalini8979 ?

**Comment by surajsahani** [comment] 2024-11-22 11:03
duplicate of #10  closing this issue now

**Closed** 2024-11-22 11:03 UTC
Labels: duplicate
